<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-02-25 21:20

$extensionPath = t3lib_extMgm::extPath('contexts');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_contexts_api_configuration' => $extensionClassesPath . 'Api/Configuration.php',
    'tx_contexts_api_model' => $extensionClassesPath . 'Api/Model.php',
    'tx_contexts_api_model_contexts' => $extensionClassesPath . 'Api/Model/Contexts.php',
	'tx_contexts_context_abstract' => $extensionClassesPath . 'Context/Abstract.php',
	'tx_contexts_context_default' => $extensionClassesPath . 'Context/Default.php',
	'tx_contexts_context_factory' => $extensionClassesPath . 'Context/Factory.php',
	'tx_contexts_context_rule' => $extensionClassesPath . 'Context/Rule.php',
	'tx_contexts_service_tca' => $extensionClassesPath . 'Service/Tca.php',
	'tx_contexts_service_tcemain' => $extensionClassesPath . 'Service/Tcemain.php',
	'tx_contexts_exception' => $extensionClassesPath . 'Exception.php',
);
?>