#!/bin/bash

# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: Netresearch DTT GmbH
## Description: Setup project for development
## Usage: setup
## Example: ddev setup

set -e

composer install
