name: Dependency Review
on:
  pull_request:
permissions: {}
jobs:
  review:
    uses: netresearch/.github/.github/workflows/dependency-review.yml@f87ee244a6e0d78c24e0bd58794563ab8d916943 # main
    permissions:
      contents: read
      pull-requests: write
