name: OpenSSF Scorecard
on:
  push:
    branches: [main]
  schedule:
    - cron: '25 6 * * 1'
permissions: {}
jobs:
  scorecard:
    uses: netresearch/.github/.github/workflows/scorecard.yml@f87ee244a6e0d78c24e0bd58794563ab8d916943 # main
    permissions:
      contents: read
      security-events: write
      id-token: write
      actions: read
