name: Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  stale:
    uses: netresearch/.github/.github/workflows/stale.yml@f87ee244a6e0d78c24e0bd58794563ab8d916943 # main
    permissions:
      issues: write
      pull-requests: write
